// АВТОГЕНЕРИРАНО од db/migrations/0000_full_schema.sql (drizzle-kit generate)
// Целосна Postgres шема — сите 44 табели. Идемпотентно: IF NOT EXISTS + try/catch на constraints.

export function getInitSql(): string[] {
  return [
    `CREATE TABLE IF NOT EXISTS "audit_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" bigint,
	"user_name" varchar(255),
	"action" varchar(50) NOT NULL,
	"entity_type" varchar(50) NOT NULL,
	"entity_id" bigint,
	"old_value" text,
	"new_value" text,
	"description" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "company_settings" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"address" text,
	"edb" varchar(20) NOT NULL,
	"embs" varchar(20),
	"bank_name" varchar(255),
	"bank_account" varchar(50),
	"phone" varchar(50),
	"email" varchar(320),
	"logo_url" text,
	"default_vat_rate" numeric(5, 2) DEFAULT '0' NOT NULL,
	"valuation_method" varchar(50) NOT NULL,
	"currency" varchar(10) NOT NULL,
	"timezone" varchar(50) NOT NULL,
	"email_imap_host" varchar(255),
	"email_imap_port" integer DEFAULT 993,
	"email_imap_secure" integer DEFAULT 1,
	"email_username" varchar(255),
	"email_password" varchar(255),
	"email_check_interval" integer DEFAULT 60,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "customers" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"company" varchar(255),
	"contact_person" varchar(255),
	"email" varchar(320),
	"phone" varchar(50),
	"address" text,
	"city" varchar(100),
	"country" varchar(100),
	"tax_number" varchar(50),
	"edb" varchar(20),
	"notes" text,
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "delivery_notes" (
	"id" serial PRIMARY KEY NOT NULL,
	"dn_number" varchar(50) NOT NULL,
	"customer_id" bigint NOT NULL,
	"order_id" bigint,
	"status" varchar(50) NOT NULL,
	"issue_date" date NOT NULL,
	"delivery_date" date,
	"total_items" integer DEFAULT 0 NOT NULL,
	"notes" text,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "delivery_notes_dn_number_unique" UNIQUE("dn_number")
);`,
    `CREATE TABLE IF NOT EXISTS "digital_certificates" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"cert_type" varchar(50) NOT NULL,
	"certificate_pem" text NOT NULL,
	"private_key_encrypted" text,
	"encryption_iv" varchar(100),
	"encryption_auth_tag" varchar(100),
	"issuer" varchar(255),
	"serial_number" varchar(100),
	"valid_from" date,
	"valid_to" date,
	"edb" varchar(20),
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"last_used_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "doc_counters" (
	"id" serial PRIMARY KEY NOT NULL,
	"kind" varchar(10) NOT NULL,
	"year" integer NOT NULL,
	"value" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "document_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"document_id" bigint NOT NULL,
	"document_type" varchar(50) NOT NULL,
	"description" varchar(500) NOT NULL,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"unit" varchar(20) NOT NULL,
	"unit_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"discount" numeric(5, 2) DEFAULT '0' NOT NULL,
	"total_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"vat_rate" numeric(5, 2) DEFAULT '0' NOT NULL,
	"product_id" bigint,
	"service_id" bigint,
	"item_type" varchar(50) NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "e_invoices" (
	"id" serial PRIMARY KEY NOT NULL,
	"invoice_id" bigint NOT NULL,
	"ujp_invoice_id" varchar(255),
	"status" varchar(50) NOT NULL,
	"xml_content" text,
	"response_message" text,
	"sent_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "email_invoices" (
	"id" serial PRIMARY KEY NOT NULL,
	"subject" varchar(500),
	"sender_email" varchar(255),
	"sender_name" varchar(255),
	"received_at" timestamp DEFAULT now() NOT NULL,
	"pdf_base64" text,
	"pdf_filename" varchar(255),
	"parsed_supplier_name" varchar(255),
	"parsed_invoice_number" varchar(100),
	"parsed_total_amount" varchar(50),
	"parsed_issue_date" varchar(20),
	"matched_supplier_id" bigint,
	"status" varchar(50) NOT NULL,
	"raw_text" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "finished_goods_stock" (
	"id" serial PRIMARY KEY NOT NULL,
	"product_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"work_order_id" bigint,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"unit_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"notes" text,
	"updated_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "incoming_invoices" (
	"id" serial PRIMARY KEY NOT NULL,
	"supplier_invoice_number" varchar(50) NOT NULL,
	"supplier_id" bigint NOT NULL,
	"po_id" bigint,
	"receipt_id" bigint,
	"status" varchar(50) NOT NULL,
	"issue_date" date,
	"received_date" date NOT NULL,
	"due_date" date,
	"subtotal" numeric(14, 2) DEFAULT '0' NOT NULL,
	"vat_rate" numeric(5, 2) DEFAULT '0' NOT NULL,
	"vat_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"currency" varchar(10) NOT NULL,
	"notes" text,
	"file_url" text,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "inventory_count_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"count_id" bigint NOT NULL,
	"material_id" bigint NOT NULL,
	"system_qty" numeric(12, 3) DEFAULT '0' NOT NULL,
	"counted_qty" numeric(12, 3),
	"difference" numeric(12, 3),
	"unit_cost" numeric(12, 2),
	"total_difference" numeric(12, 2),
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "inventory_counts" (
	"id" serial PRIMARY KEY NOT NULL,
	"count_number" varchar(50) NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"status" varchar(50) NOT NULL,
	"count_date" date NOT NULL,
	"notes" text,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "inventory_counts_count_number_unique" UNIQUE("count_number")
);`,
    `CREATE TABLE IF NOT EXISTS "inventory_transactions" (
	"id" serial PRIMARY KEY NOT NULL,
	"material_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"type" varchar(50) NOT NULL,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"unit_cost" numeric(12, 2),
	"total_cost" numeric(12, 2),
	"reference" varchar(255),
	"source_doc_type" varchar(50),
	"source_doc_id" bigint,
	"notes" text,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "invoices" (
	"id" serial PRIMARY KEY NOT NULL,
	"invoice_number" varchar(50) NOT NULL,
	"customer_id" bigint NOT NULL,
	"order_id" bigint,
	"work_order_id" bigint,
	"status" varchar(50) NOT NULL,
	"invoice_type" varchar(50) NOT NULL,
	"issue_date" date NOT NULL,
	"due_date" date,
	"subtotal" numeric(14, 2) DEFAULT '0' NOT NULL,
	"vat_rate" numeric(5, 2) DEFAULT '0' NOT NULL,
	"vat_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"currency" varchar(10) NOT NULL,
	"notes" text,
	"e_invoice_id" varchar(255),
	"original_invoice_id" bigint,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "invoices_invoice_number_unique" UNIQUE("invoice_number")
);`,
    `CREATE TABLE IF NOT EXISTS "labor_rates" (
	"id" serial PRIMARY KEY NOT NULL,
	"role" varchar(255) NOT NULL,
	"role_code" varchar(50) NOT NULL,
	"cost_per_hour" numeric(12, 2) DEFAULT '0' NOT NULL,
	"gross_salary" numeric(12, 2) DEFAULT '0' NOT NULL,
	"contributions_pct" numeric(5, 2) DEFAULT '0' NOT NULL,
	"description" text,
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "labor_rates_role_code_unique" UNIQUE("role_code")
);`,
    `CREATE TABLE IF NOT EXISTS "machines" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"code" varchar(50) NOT NULL,
	"type" varchar(50) NOT NULL,
	"cost_per_hour" numeric(12, 2) DEFAULT '0' NOT NULL,
	"cost_per_meter" numeric(12, 2) DEFAULT '0' NOT NULL,
	"annual_amortization" numeric(14, 2) DEFAULT '0' NOT NULL,
	"annual_electricity" numeric(14, 2) DEFAULT '0' NOT NULL,
	"annual_gas" numeric(14, 2) DEFAULT '0' NOT NULL,
	"annual_service" numeric(14, 2) DEFAULT '0' NOT NULL,
	"annual_hours" numeric(8, 2) DEFAULT '0' NOT NULL,
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "machines_code_unique" UNIQUE("code")
);`,
    `CREATE TABLE IF NOT EXISTS "material_lots" (
	"id" serial PRIMARY KEY NOT NULL,
	"material_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"receipt_id" bigint,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"remaining_qty" numeric(12, 3) DEFAULT '0' NOT NULL,
	"unit_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"landed_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"date" date NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "material_stock" (
	"id" serial PRIMARY KEY NOT NULL,
	"material_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"avg_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "materials" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"code" varchar(100) NOT NULL,
	"type" varchar(50) NOT NULL,
	"unit" varchar(50) NOT NULL,
	"description" text,
	"min_stock" numeric(12, 3) DEFAULT '0' NOT NULL,
	"current_stock" numeric(12, 3) DEFAULT '0' NOT NULL,
	"avg_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"last_purchase_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"location" varchar(100),
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "materials_code_unique" UNIQUE("code")
);`,
    `CREATE TABLE IF NOT EXISTS "order_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"order_id" bigint NOT NULL,
	"description" varchar(500) NOT NULL,
	"drawing_number" varchar(100),
	"quantity" integer NOT NULL,
	"unit_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"cost_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"margin_amount" numeric(12, 2) DEFAULT '0' NOT NULL,
	"material" varchar(255),
	"dimensions" varchar(255),
	"product_id" bigint,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"order_number" varchar(50) NOT NULL,
	"customer_id" bigint NOT NULL,
	"quote_id" bigint,
	"status" varchar(50) NOT NULL,
	"priority" varchar(50) NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"cost_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"margin_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"margin_percent" numeric(5, 2) DEFAULT '0' NOT NULL,
	"delivery_date" date,
	"notes" text,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "orders_order_number_unique" UNIQUE("order_number")
);`,
    `CREATE TABLE IF NOT EXISTS "overhead" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"rate_type" varchar(50) NOT NULL,
	"rate_value" numeric(12, 4) DEFAULT '0' NOT NULL,
	"annual_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"description" text,
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "parsed_invoices" (
	"id" serial PRIMARY KEY NOT NULL,
	"original_file_name" varchar(500) NOT NULL,
	"supplier_name" varchar(255),
	"invoice_number" varchar(100),
	"issue_date" date,
	"due_date" date,
	"total_amount" numeric(14, 2),
	"vat_amount" numeric(14, 2),
	"currency" varchar(10),
	"raw_text" text,
	"file_url" text,
	"document_type" varchar(50) NOT NULL,
	"status" varchar(50) NOT NULL,
	"matched_invoice_id" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "parsed_receipt_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"parsed_invoice_id" bigint NOT NULL,
	"raw_description" text NOT NULL,
	"matched_material_id" bigint,
	"matched_material_name" varchar(255),
	"match_confidence" numeric(5, 2) DEFAULT '0' NOT NULL,
	"quantity" numeric(12, 3),
	"unit" varchar(20),
	"unit_price" numeric(12, 2),
	"total_price" numeric(12, 2),
	"vat_rate" numeric(5, 2),
	"is_confirmed" varchar(50) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "product_components" (
	"id" serial PRIMARY KEY NOT NULL,
	"product_id" bigint NOT NULL,
	"kind" varchar(50) NOT NULL,
	"ref_id" bigint NOT NULL,
	"per_unit" numeric(12, 6) DEFAULT '0' NOT NULL,
	"waste_pct" numeric(5, 2) DEFAULT '0' NOT NULL,
	"scale" varchar(50) NOT NULL,
	"notes" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "products" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"code" varchar(100) NOT NULL,
	"category" varchar(50) NOT NULL,
	"description" text,
	"unit" varchar(50) NOT NULL,
	"basis" varchar(50) NOT NULL,
	"default_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"material_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"labor_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"machine_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"overhead_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "products_code_unique" UNIQUE("code")
);`,
    `CREATE TABLE IF NOT EXISTS "purchase_order_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"purchase_order_id" bigint NOT NULL,
	"material_id" bigint NOT NULL,
	"description" varchar(500) NOT NULL,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"unit_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"received_quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "purchase_orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"po_number" varchar(50) NOT NULL,
	"supplier_id" bigint NOT NULL,
	"status" varchar(50) NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"expected_date" date,
	"notes" text,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "purchase_orders_po_number_unique" UNIQUE("po_number")
);`,
    `CREATE TABLE IF NOT EXISTS "quotation_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"quotation_id" bigint NOT NULL,
	"item_type" varchar(50) NOT NULL,
	"reference_id" bigint,
	"description" varchar(500) NOT NULL,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"unit" varchar(20) NOT NULL,
	"unit_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"unit_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"vat_rate" numeric(5, 2) DEFAULT '0' NOT NULL,
	"notes" text,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "quotations" (
	"id" serial PRIMARY KEY NOT NULL,
	"quote_number" varchar(50) NOT NULL,
	"customer_id" bigint NOT NULL,
	"status" varchar(50) NOT NULL,
	"subtotal" numeric(14, 2) DEFAULT '0' NOT NULL,
	"cost_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"margin_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"margin_percent" numeric(5, 2) DEFAULT '0' NOT NULL,
	"vat_rate" numeric(5, 2) DEFAULT '0' NOT NULL,
	"vat_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"currency" varchar(10) NOT NULL,
	"valid_until" date,
	"delivery_days" integer DEFAULT 14,
	"payment_terms" varchar(255),
	"notes" text,
	"converted_order_id" bigint,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "quotations_quote_number_unique" UNIQUE("quote_number")
);`,
    `CREATE TABLE IF NOT EXISTS "receipt_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"receipt_id" bigint NOT NULL,
	"material_id" bigint NOT NULL,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"unit" varchar(20) NOT NULL,
	"unit_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total_price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"landed_cost_alloc" numeric(12, 2) DEFAULT '0' NOT NULL,
	"vat_rate" numeric(5, 2) DEFAULT '0' NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "receipts" (
	"id" serial PRIMARY KEY NOT NULL,
	"receipt_number" varchar(50) NOT NULL,
	"supplier_id" bigint,
	"po_id" bigint,
	"warehouse_id" bigint NOT NULL,
	"status" varchar(50) NOT NULL,
	"receipt_date" date NOT NULL,
	"supplier_doc_number" varchar(100),
	"transport_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"customs_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"other_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"notes" text,
	"file_url" text,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "receipts_receipt_number_unique" UNIQUE("receipt_number")
);`,
    `CREATE TABLE IF NOT EXISTS "services" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"code" varchar(100) NOT NULL,
	"type" varchar(50) NOT NULL,
	"unit" varchar(50) NOT NULL,
	"description" text,
	"cost_rate" numeric(12, 2) DEFAULT '0' NOT NULL,
	"sale_rate" numeric(12, 2) DEFAULT '0' NOT NULL,
	"machine_id" bigint,
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "services_code_unique" UNIQUE("code")
);`,
    `CREATE TABLE IF NOT EXISTS "stock_transfer_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"transfer_id" bigint NOT NULL,
	"material_id" bigint NOT NULL,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"unit_cost" numeric(12, 2),
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "stock_transfers" (
	"id" serial PRIMARY KEY NOT NULL,
	"transfer_number" varchar(50) NOT NULL,
	"from_warehouse_id" bigint NOT NULL,
	"to_warehouse_id" bigint NOT NULL,
	"status" varchar(50) NOT NULL,
	"transfer_date" date NOT NULL,
	"notes" text,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "stock_transfers_transfer_number_unique" UNIQUE("transfer_number")
);`,
    `CREATE TABLE IF NOT EXISTS "suppliers" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"edb" varchar(20),
	"contact_person" varchar(255),
	"email" varchar(320),
	"phone" varchar(50),
	"address" text,
	"city" varchar(100),
	"country" varchar(100),
	"payment_terms" varchar(100),
	"default_currency" varchar(10),
	"materials" text,
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "unit_conversions" (
	"id" serial PRIMARY KEY NOT NULL,
	"from_unit_id" bigint NOT NULL,
	"to_unit_id" bigint NOT NULL,
	"factor" numeric(18, 8) DEFAULT '0' NOT NULL,
	"material_type" varchar(50),
	"description" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "units" (
	"id" serial PRIMARY KEY NOT NULL,
	"code" varchar(20) NOT NULL,
	"name" varchar(100) NOT NULL,
	"name_mk" varchar(100),
	"category" varchar(50) NOT NULL,
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "units_code_unique" UNIQUE("code")
);`,
    `CREATE TABLE IF NOT EXISTS "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"union_id" varchar(255) NOT NULL,
	"name" varchar(255),
	"email" varchar(320),
	"avatar" text,
	"role" varchar(50) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_sign_in_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_union_id_unique" UNIQUE("union_id")
);`,
    `CREATE TABLE IF NOT EXISTS "warehouses" (
	"id" serial PRIMARY KEY NOT NULL,
	"code" varchar(20) NOT NULL,
	"name" varchar(255) NOT NULL,
	"type" varchar(50) NOT NULL,
	"address" text,
	"is_active" varchar(50) DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "warehouses_code_unique" UNIQUE("code")
);`,
    `CREATE TABLE IF NOT EXISTS "work_order_materials" (
	"id" serial PRIMARY KEY NOT NULL,
	"work_order_id" bigint NOT NULL,
	"material_id" bigint NOT NULL,
	"quantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"unit_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total_cost" numeric(12, 2) DEFAULT '0' NOT NULL,
	"is_actual" varchar(50) NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "work_order_operations" (
	"id" serial PRIMARY KEY NOT NULL,
	"work_order_id" bigint NOT NULL,
	"operation" varchar(50) NOT NULL,
	"sequence" integer NOT NULL,
	"description" varchar(500),
	"estimated_time" numeric(8, 2),
	"actual_time" numeric(8, 2),
	"estimated_qty" numeric(12, 3),
	"actual_qty" numeric(12, 3),
	"qty_unit" varchar(20),
	"status" varchar(50) NOT NULL,
	"operator" varchar(255),
	"cost_rate" numeric(12, 2) DEFAULT '0' NOT NULL,
	"cost_amount" numeric(12, 2) DEFAULT '0' NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);`,
    `CREATE TABLE IF NOT EXISTS "work_orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"wo_number" varchar(50) NOT NULL,
	"order_id" bigint,
	"description" varchar(500) NOT NULL,
	"status" varchar(50) NOT NULL,
	"priority" varchar(50) NOT NULL,
	"planned_start" date,
	"planned_end" date,
	"actual_start" date,
	"actual_end" date,
	"assigned_to" varchar(255),
	"cost_amount" numeric(14, 2) DEFAULT '0' NOT NULL,
	"notes" text,
	"created_by" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "work_orders_wo_number_unique" UNIQUE("wo_number")
);`,
    `INSERT INTO "warehouses" ("code","name","type","address","is_active") SELECT 'GL-MAT','Главен Магацин - Материјали','raw_materials','Скопје','active' WHERE NOT EXISTS (SELECT 1 FROM "warehouses" WHERE "code"='GL-MAT')`,
    `INSERT INTO "warehouses" ("code","name","type","address","is_active") SELECT 'GL-PROD','Главен Магацин - Производи','finished_goods','Скопје','active' WHERE NOT EXISTS (SELECT 1 FROM "warehouses" WHERE "code"='GL-PROD')`,
    `INSERT INTO "units" ("code","name","name_mk","category","is_active") SELECT 'kg','Килограм','Килограм','weight','active' WHERE NOT EXISTS (SELECT 1 FROM "units" WHERE "code"='kg')`,
    `INSERT INTO "units" ("code","name","name_mk","category","is_active") SELECT 'm','Метар','Метар','length','active' WHERE NOT EXISTS (SELECT 1 FROM "units" WHERE "code"='m')`,
    `INSERT INTO "units" ("code","name","name_mk","category","is_active") SELECT 'm2','Квадратен метар','Квадратен метар','area','active' WHERE NOT EXISTS (SELECT 1 FROM "units" WHERE "code"='m2')`,
    `INSERT INTO "units" ("code","name","name_mk","category","is_active") SELECT 'kom','Комад','Комад','piece','active' WHERE NOT EXISTS (SELECT 1 FROM "units" WHERE "code"='kom')`,
    `INSERT INTO "units" ("code","name","name_mk","category","is_active") SELECT 'l','Литар','Литар','volume','active' WHERE NOT EXISTS (SELECT 1 FROM "units" WHERE "code"='l')`,
    `INSERT INTO "units" ("code","name","name_mk","category","is_active") SELECT 'h','Час','Час','time','active' WHERE NOT EXISTS (SELECT 1 FROM "units" WHERE "code"='h')`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "user_id" bigint`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "user_name" varchar(255)`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "action" varchar(50)`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "entity_type" varchar(50)`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "entity_id" bigint`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "old_value" text`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "new_value" text`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "description" text`,
    `ALTER TABLE "audit_log" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "address" text`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "edb" varchar(20)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "embs" varchar(20)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "bank_name" varchar(255)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "bank_account" varchar(50)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "phone" varchar(50)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "email" varchar(320)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "logo_url" text`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "default_vat_rate" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "valuation_method" varchar(50)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "currency" varchar(10)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "timezone" varchar(50)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "email_imap_host" varchar(255)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "email_imap_port" integer DEFAULT 993`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "email_imap_secure" integer DEFAULT 1`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "email_username" varchar(255)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "email_password" varchar(255)`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "email_check_interval" integer DEFAULT 60`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "company_settings" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "company" varchar(255)`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "contact_person" varchar(255)`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "email" varchar(320)`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "phone" varchar(50)`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "address" text`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "city" varchar(100)`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "country" varchar(100)`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "tax_number" varchar(50)`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "edb" varchar(20)`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "customers" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "dn_number" varchar(50)`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "customer_id" bigint`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "order_id" bigint`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "issue_date" date`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "delivery_date" date`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "total_items" integer DEFAULT 0`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "delivery_notes" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "cert_type" varchar(50)`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "certificate_pem" text`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "private_key_encrypted" text`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "encryption_iv" varchar(100)`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "encryption_auth_tag" varchar(100)`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "issuer" varchar(255)`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "serial_number" varchar(100)`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "valid_from" date`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "valid_to" date`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "edb" varchar(20)`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "last_used_at" timestamp`,
    `ALTER TABLE "digital_certificates" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "doc_counters" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "doc_counters" ADD COLUMN IF NOT EXISTS "kind" varchar(10)`,
    `ALTER TABLE "doc_counters" ADD COLUMN IF NOT EXISTS "year" integer`,
    `ALTER TABLE "doc_counters" ADD COLUMN IF NOT EXISTS "value" integer DEFAULT 0`,
    `ALTER TABLE "doc_counters" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "doc_counters" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "document_id" bigint`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "document_type" varchar(50)`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "description" varchar(500)`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "unit" varchar(20)`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "unit_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "discount" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "total_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "vat_rate" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "product_id" bigint`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "service_id" bigint`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "item_type" varchar(50)`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "document_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "e_invoices" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "e_invoices" ADD COLUMN IF NOT EXISTS "invoice_id" bigint`,
    `ALTER TABLE "e_invoices" ADD COLUMN IF NOT EXISTS "ujp_invoice_id" varchar(255)`,
    `ALTER TABLE "e_invoices" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "e_invoices" ADD COLUMN IF NOT EXISTS "xml_content" text`,
    `ALTER TABLE "e_invoices" ADD COLUMN IF NOT EXISTS "response_message" text`,
    `ALTER TABLE "e_invoices" ADD COLUMN IF NOT EXISTS "sent_at" timestamp`,
    `ALTER TABLE "e_invoices" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "subject" varchar(500)`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "sender_email" varchar(255)`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "sender_name" varchar(255)`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "received_at" timestamp DEFAULT now()`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "pdf_base64" text`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "pdf_filename" varchar(255)`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "parsed_supplier_name" varchar(255)`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "parsed_invoice_number" varchar(100)`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "parsed_total_amount" varchar(50)`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "parsed_issue_date" varchar(20)`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "matched_supplier_id" bigint`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "raw_text" text`,
    `ALTER TABLE "email_invoices" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "finished_goods_stock" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "finished_goods_stock" ADD COLUMN IF NOT EXISTS "product_id" bigint`,
    `ALTER TABLE "finished_goods_stock" ADD COLUMN IF NOT EXISTS "warehouse_id" bigint`,
    `ALTER TABLE "finished_goods_stock" ADD COLUMN IF NOT EXISTS "work_order_id" bigint`,
    `ALTER TABLE "finished_goods_stock" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "finished_goods_stock" ADD COLUMN IF NOT EXISTS "unit_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "finished_goods_stock" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "finished_goods_stock" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "supplier_invoice_number" varchar(50)`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "supplier_id" bigint`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "po_id" bigint`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "receipt_id" bigint`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "issue_date" date`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "received_date" date`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "due_date" date`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "subtotal" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "vat_rate" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "vat_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "total_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "currency" varchar(10)`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "file_url" text`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "incoming_invoices" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "count_id" bigint`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "material_id" bigint`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "system_qty" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "counted_qty" numeric(12, 3)`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "difference" numeric(12, 3)`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "unit_cost" numeric(12, 2)`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "total_difference" numeric(12, 2)`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "inventory_count_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "inventory_counts" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "inventory_counts" ADD COLUMN IF NOT EXISTS "count_number" varchar(50)`,
    `ALTER TABLE "inventory_counts" ADD COLUMN IF NOT EXISTS "warehouse_id" bigint`,
    `ALTER TABLE "inventory_counts" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "inventory_counts" ADD COLUMN IF NOT EXISTS "count_date" date`,
    `ALTER TABLE "inventory_counts" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "inventory_counts" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "inventory_counts" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "material_id" bigint`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "warehouse_id" bigint`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "type" varchar(50)`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "unit_cost" numeric(12, 2)`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "total_cost" numeric(12, 2)`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "reference" varchar(255)`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "source_doc_type" varchar(50)`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "source_doc_id" bigint`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "inventory_transactions" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "invoice_number" varchar(50)`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "customer_id" bigint`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "order_id" bigint`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "work_order_id" bigint`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "invoice_type" varchar(50)`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "issue_date" date`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "due_date" date`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "subtotal" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "vat_rate" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "vat_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "total_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "currency" varchar(10)`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "e_invoice_id" varchar(255)`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "original_invoice_id" bigint`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "labor_rates" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "labor_rates" ADD COLUMN IF NOT EXISTS "role" varchar(255)`,
    `ALTER TABLE "labor_rates" ADD COLUMN IF NOT EXISTS "role_code" varchar(50)`,
    `ALTER TABLE "labor_rates" ADD COLUMN IF NOT EXISTS "cost_per_hour" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "labor_rates" ADD COLUMN IF NOT EXISTS "gross_salary" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "labor_rates" ADD COLUMN IF NOT EXISTS "contributions_pct" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "labor_rates" ADD COLUMN IF NOT EXISTS "description" text`,
    `ALTER TABLE "labor_rates" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "labor_rates" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "code" varchar(50)`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "type" varchar(50)`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "cost_per_hour" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "cost_per_meter" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "annual_amortization" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "annual_electricity" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "annual_gas" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "annual_service" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "annual_hours" numeric(8, 2) DEFAULT '0'`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "machines" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "material_id" bigint`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "warehouse_id" bigint`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "receipt_id" bigint`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "remaining_qty" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "unit_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "landed_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "date" date`,
    `ALTER TABLE "material_lots" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "material_stock" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "material_stock" ADD COLUMN IF NOT EXISTS "material_id" bigint`,
    `ALTER TABLE "material_stock" ADD COLUMN IF NOT EXISTS "warehouse_id" bigint`,
    `ALTER TABLE "material_stock" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "material_stock" ADD COLUMN IF NOT EXISTS "avg_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "material_stock" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "material_stock" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "code" varchar(100)`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "type" varchar(50)`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "unit" varchar(50)`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "description" text`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "min_stock" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "current_stock" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "avg_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "last_purchase_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "location" varchar(100)`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "materials" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "order_id" bigint`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "description" varchar(500)`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "drawing_number" varchar(100)`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "quantity" integer`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "unit_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "total_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "cost_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "margin_amount" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "material" varchar(255)`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "dimensions" varchar(255)`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "product_id" bigint`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "order_number" varchar(50)`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "customer_id" bigint`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "quote_id" bigint`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "priority" varchar(50)`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "total_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "cost_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "margin_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "margin_percent" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "delivery_date" date`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "overhead" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "overhead" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "overhead" ADD COLUMN IF NOT EXISTS "rate_type" varchar(50)`,
    `ALTER TABLE "overhead" ADD COLUMN IF NOT EXISTS "rate_value" numeric(12, 4) DEFAULT '0'`,
    `ALTER TABLE "overhead" ADD COLUMN IF NOT EXISTS "annual_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "overhead" ADD COLUMN IF NOT EXISTS "description" text`,
    `ALTER TABLE "overhead" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "overhead" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "original_file_name" varchar(500)`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "supplier_name" varchar(255)`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "invoice_number" varchar(100)`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "issue_date" date`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "due_date" date`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "total_amount" numeric(14, 2)`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "vat_amount" numeric(14, 2)`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "currency" varchar(10)`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "raw_text" text`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "file_url" text`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "document_type" varchar(50)`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "matched_invoice_id" bigint`,
    `ALTER TABLE "parsed_invoices" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "parsed_invoice_id" bigint`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "raw_description" text`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "matched_material_id" bigint`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "matched_material_name" varchar(255)`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "match_confidence" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3)`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "unit" varchar(20)`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "unit_price" numeric(12, 2)`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "total_price" numeric(12, 2)`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "vat_rate" numeric(5, 2)`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "is_confirmed" varchar(50)`,
    `ALTER TABLE "parsed_receipt_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "product_id" bigint`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "kind" varchar(50)`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "ref_id" bigint`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "per_unit" numeric(12, 6) DEFAULT '0'`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "waste_pct" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "scale" varchar(50)`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0`,
    `ALTER TABLE "product_components" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "code" varchar(100)`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "category" varchar(50)`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "description" text`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "unit" varchar(50)`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "basis" varchar(50)`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "default_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "material_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "labor_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "machine_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "overhead_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "total_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "purchase_order_id" bigint`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "material_id" bigint`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "description" varchar(500)`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "unit_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "total_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "received_quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "purchase_order_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "po_number" varchar(50)`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "supplier_id" bigint`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "total_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "expected_date" date`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "purchase_orders" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "quotation_id" bigint`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "item_type" varchar(50)`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "reference_id" bigint`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "description" varchar(500)`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "unit" varchar(20)`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "unit_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "unit_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "total_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "total_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "vat_rate" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0`,
    `ALTER TABLE "quotation_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "quote_number" varchar(50)`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "customer_id" bigint`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "subtotal" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "cost_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "margin_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "margin_percent" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "vat_rate" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "vat_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "total_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "currency" varchar(10)`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "valid_until" date`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "delivery_days" integer DEFAULT 14`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "payment_terms" varchar(255)`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "converted_order_id" bigint`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "quotations" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "receipt_id" bigint`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "material_id" bigint`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "unit" varchar(20)`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "unit_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "total_price" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "landed_cost_alloc" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "vat_rate" numeric(5, 2) DEFAULT '0'`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "receipt_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "receipt_number" varchar(50)`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "supplier_id" bigint`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "po_id" bigint`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "warehouse_id" bigint`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "receipt_date" date`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "supplier_doc_number" varchar(100)`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "transport_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "customs_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "other_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "total_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "file_url" text`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "receipts" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "code" varchar(100)`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "type" varchar(50)`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "unit" varchar(50)`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "description" text`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "cost_rate" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "sale_rate" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "machine_id" bigint`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "services" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "stock_transfer_items" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "stock_transfer_items" ADD COLUMN IF NOT EXISTS "transfer_id" bigint`,
    `ALTER TABLE "stock_transfer_items" ADD COLUMN IF NOT EXISTS "material_id" bigint`,
    `ALTER TABLE "stock_transfer_items" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "stock_transfer_items" ADD COLUMN IF NOT EXISTS "unit_cost" numeric(12, 2)`,
    `ALTER TABLE "stock_transfer_items" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "stock_transfer_items" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "stock_transfers" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "stock_transfers" ADD COLUMN IF NOT EXISTS "transfer_number" varchar(50)`,
    `ALTER TABLE "stock_transfers" ADD COLUMN IF NOT EXISTS "from_warehouse_id" bigint`,
    `ALTER TABLE "stock_transfers" ADD COLUMN IF NOT EXISTS "to_warehouse_id" bigint`,
    `ALTER TABLE "stock_transfers" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "stock_transfers" ADD COLUMN IF NOT EXISTS "transfer_date" date`,
    `ALTER TABLE "stock_transfers" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "stock_transfers" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "stock_transfers" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "edb" varchar(20)`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "contact_person" varchar(255)`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "email" varchar(320)`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "phone" varchar(50)`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "address" text`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "city" varchar(100)`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "country" varchar(100)`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "payment_terms" varchar(100)`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "default_currency" varchar(10)`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "materials" text`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "suppliers" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "unit_conversions" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "unit_conversions" ADD COLUMN IF NOT EXISTS "from_unit_id" bigint`,
    `ALTER TABLE "unit_conversions" ADD COLUMN IF NOT EXISTS "to_unit_id" bigint`,
    `ALTER TABLE "unit_conversions" ADD COLUMN IF NOT EXISTS "factor" numeric(18, 8) DEFAULT '0'`,
    `ALTER TABLE "unit_conversions" ADD COLUMN IF NOT EXISTS "material_type" varchar(50)`,
    `ALTER TABLE "unit_conversions" ADD COLUMN IF NOT EXISTS "description" text`,
    `ALTER TABLE "unit_conversions" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "units" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "units" ADD COLUMN IF NOT EXISTS "code" varchar(20)`,
    `ALTER TABLE "units" ADD COLUMN IF NOT EXISTS "name" varchar(100)`,
    `ALTER TABLE "units" ADD COLUMN IF NOT EXISTS "name_mk" varchar(100)`,
    `ALTER TABLE "units" ADD COLUMN IF NOT EXISTS "category" varchar(50)`,
    `ALTER TABLE "units" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "units" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "union_id" varchar(255)`,
    `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email" varchar(320)`,
    `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "avatar" text`,
    `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "role" varchar(50)`,
    `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "last_sign_in_at" timestamp DEFAULT now()`,
    `ALTER TABLE "warehouses" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "warehouses" ADD COLUMN IF NOT EXISTS "code" varchar(20)`,
    `ALTER TABLE "warehouses" ADD COLUMN IF NOT EXISTS "name" varchar(255)`,
    `ALTER TABLE "warehouses" ADD COLUMN IF NOT EXISTS "type" varchar(50)`,
    `ALTER TABLE "warehouses" ADD COLUMN IF NOT EXISTS "address" text`,
    `ALTER TABLE "warehouses" ADD COLUMN IF NOT EXISTS "is_active" varchar(50) DEFAULT 'active'`,
    `ALTER TABLE "warehouses" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "work_order_materials" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "work_order_materials" ADD COLUMN IF NOT EXISTS "work_order_id" bigint`,
    `ALTER TABLE "work_order_materials" ADD COLUMN IF NOT EXISTS "material_id" bigint`,
    `ALTER TABLE "work_order_materials" ADD COLUMN IF NOT EXISTS "quantity" numeric(12, 3) DEFAULT '0'`,
    `ALTER TABLE "work_order_materials" ADD COLUMN IF NOT EXISTS "unit_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "work_order_materials" ADD COLUMN IF NOT EXISTS "total_cost" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "work_order_materials" ADD COLUMN IF NOT EXISTS "is_actual" varchar(50)`,
    `ALTER TABLE "work_order_materials" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "work_order_materials" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "work_order_id" bigint`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "operation" varchar(50)`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "sequence" integer`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "description" varchar(500)`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "estimated_time" numeric(8, 2)`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "actual_time" numeric(8, 2)`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "estimated_qty" numeric(12, 3)`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "actual_qty" numeric(12, 3)`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "qty_unit" varchar(20)`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "operator" varchar(255)`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "cost_rate" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "cost_amount" numeric(12, 2) DEFAULT '0'`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "work_order_operations" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "id" serial PRIMARY KEY`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "wo_number" varchar(50)`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "order_id" bigint`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "description" varchar(500)`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "status" varchar(50)`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "priority" varchar(50)`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "planned_start" date`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "planned_end" date`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "actual_start" date`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "actual_end" date`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "assigned_to" varchar(255)`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "cost_amount" numeric(14, 2) DEFAULT '0'`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "notes" text`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "created_by" bigint`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "created_at" timestamp DEFAULT now()`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "updated_at" timestamp DEFAULT now()`,
    `ALTER TABLE "company_settings" ALTER COLUMN "currency" SET DEFAULT 'MKD'`,
    `ALTER TABLE "delivery_notes" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "e_invoices" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "email_invoices" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "incoming_invoices" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "incoming_invoices" ALTER COLUMN "currency" SET DEFAULT 'MKD'`,
    `ALTER TABLE "inventory_counts" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "invoices" ALTER COLUMN "currency" SET DEFAULT 'MKD'`,
    `ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "orders" ALTER COLUMN "priority" SET DEFAULT 'normal'`,
    `ALTER TABLE "parsed_invoices" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "parsed_invoices" ALTER COLUMN "currency" SET DEFAULT 'MKD'`,
    `ALTER TABLE "purchase_orders" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "quotations" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "quotations" ALTER COLUMN "currency" SET DEFAULT 'MKD'`,
    `ALTER TABLE "receipts" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "stock_transfers" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "work_order_operations" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "work_orders" ALTER COLUMN "status" SET DEFAULT 'pending'`,
    `ALTER TABLE "work_orders" ALTER COLUMN "priority" SET DEFAULT 'normal'`,
    `ALTER TABLE "work_orders" ADD COLUMN IF NOT EXISTS "quotation_id" bigint`,
  ];
}
